server:
  port: 8082

spring:
  application:
    name: api-gastos
  datasource:
    url: jdbc:mysql://localhost:3306/gastos_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
