server:
  port: 8081

spring:
  application:
    name: api-cuidados
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_cuidado_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: api_cuidados_db
    password: apiCuidadosdb
  jpa:
    show-sql: true
