server:
  port: 8086

spring:
  application:
    name: api-rutinas
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_rutinas_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: api_rutinas_db
    password: apiRutinasdb
