server:
  port: 8084

spring:
  application:
    name: api-citas
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_citas_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: api_citas_db_user
    password: apiCitasdb
  jpa:
    show-sql: true

  mail:
    host: ${SMTP_HOST:smtp.mailtrap.io}
    port: ${SMTP_PORT:2525}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

