server:
  port: 8082

spring:
  application:
    name: api-gastos
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_gastos_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: api_gastos_db
    password: apiGastosdb
