server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_cuidado_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: api_cuidados_db
    password: apiCuidadosdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

security:
  jwt:
    secret: dGhpc19pc19hX3NhZmVfZGV2X3NlY3JldF9iYXNlNjQ=

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html