server:
  port: 8080

spring:
  application:
    name: api-usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true

# JWT (placeholders; mueve a Vault o a variables de entorno en prod)
security:
  jwt:
    secret: ${JWT_SECRET:change-me}
    expiration: ${JWT_EXP_MS:86400000} # 24h

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
