server:
  port: 8080

spring:
  application:
    name: api-usuarios
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_usuario_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: api_usuario_db
    password: apiUsuariodb
  jpa:
    show-sql: true