server:
  port: 8081

spring:
  application:
    name: api-cuidados
  datasource:
    url: jdbc:mysql://localhost:3306/cuidados_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: false
