server:
  port: 8080

spring:
  application:
    name: api-usuarios

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_usuario_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Madrid
    username: api_usuario_db
    password: apiUsuariodb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Europe/Madrid  

app:
  jwt:
    secret: dGhpc19pc19hX3NhZmVfZGV2X3NlY3JldF9iYXNlNjQ=
    expiration-ms: 259200000

google:
  client-id: ${GOOGLE_CLIENT_ID:default-client-id}
  
facebook:
  client-id: ${FACEBOOK_CLIENT_ID:}
  client-secret: ${FACEBOOK_CLIENT_SECRET:}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html



