spring:
  application:
    name: api-bff

server:
  port: 8087

feign:
  hystrix:
    enabled: true

# URLs de microservicios internos (modo local)
services:
  usuarios-service: http://localhost:8080/api/v1
  cuidados-service: http://localhost:8081/api/v1
  gastos-service: http://localhost:8082/api/v1
  hitos-service: http://localhost:8083/api/v1
  citas-service: http://localhost:8084/api/v1
  diario-service: http://localhost:8085/api/v1
  rutinas-service: http://localhost:8086/api/v1
 
#  profile-service: http://localhost:8091

security:
  jwt:
    secret: dGhpc19pc19hX3NhZmVfZGV2X3NlY3JldF9iYXNlNjQ=
    expiration-ms: 259200000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      
# CORS simple para React en dev
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
      
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
