server:
  port: 8084

spring:
  application:
    name: api-citas
  datasource:
    url: jdbc:mysql://localhost:3306/citas_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  mail:
    host: ${SMTP_HOST:smtp.mailtrap.io}
    port: ${SMTP_PORT:2525}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
