server:
  port: 8086

spring:
  application:
    name: api-rutinas
  datasource:
    url: jdbc:mysql://localhost:3306/rutinas_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
