server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_gastos_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: api_gastos_db
    password: apiGastosdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

security:
  jwt:
    secret: dGhpc19pc19hX3NhZmVfZGV2X3NlY3JldF9iYXNlNjQ=
    expiration-ms: 259200000  # ⇐ o 'expiration' si prefieres Opción A

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
