spring:
  application:
    name: api-bff

server:
  port: 8087

feign:
  hystrix:
    enabled: true

# URLs de microservicios internos (modo local)
services:
  cuidados-service: http://localhost:8081
  citas-service: http://localhost:8084
  rutinas-service: http://localhost:8086
#  profile-service: http://localhost:8091

jwt:
  secret: dGhpc19pc19hX3NhZmVfZGV2X3NlY3JldF9iYXNlNjQ=
  expiration: 3600000 # 1 hora en ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.babytrackmaster.apibff: DEBUG
