server:
  port: 8085

spring:
  application:
    name: api-diario
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_diario_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: api_diario_db
    password: apiDiariodb

storage:
  images:
    base-path: ${IMAGES_PATH:./uploads/diario}
