server:
  port: 8083

spring:
  application:
    name: api-hitos
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_hitos_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: api_hitos_db
    password: apiHitosdb
# Para subida de imágenes más adelante
storage:
  images:
    base-path: ${IMAGES_PATH:./uploads/hitos}
